#!/usr/bin/env python3
import argparse

from pg_db_tools import dot_command
from pg_db_tools import sql_command


def main():
    parser = argparse.ArgumentParser()

    subparsers = parser.add_subparsers()

    dot_command.setup_command_parser(subparsers)
    sql_command.setup_command_parser(subparsers)

    args = parser.parse_args()

    args.cmd(args)


if __name__ == '__main__':
    main()
