#!/usr/bin/env python3
import sys
import argparse

import yaml

from pg_db_tools.dot_renderer import render_dot
from pg_db_tools.sql_renderer import render_sql


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('infile', type=argparse.FileType('r'))

    parser.add_argument('--output-type', '-t', choices=renderer_map.keys(), default='sql')

    parser.add_argument('--output-file', '-o', help='write output to file', default=sys.stdout)

    args = parser.parse_args()

    data = yaml.load(args.infile)

    rendered_chunks = renderer_map.get(args.output_type)(data)

    args.output_file.writelines(rendered_chunks)


renderer_map = {
    'sql': render_sql,
    'dot': render_dot
}


if __name__ == '__main__':
    main()
